"""
Converts colab_rag_api.py into a proper Jupyter Notebook (.ipynb) for Google Colab.
Run: venv\Scripts\python.exe convert_to_notebook.py
"""
import json

def code_cell(source_lines):
    if isinstance(source_lines, str):
        source_lines = [source_lines]
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": ""},
        "outputs": [],
        "source": source_lines
    }

def markdown_cell(text):
    return {
        "cell_type": "markdown",
        "metadata": {"id": ""},
        "source": [text]
    }

cells = []

# ── Cell 0: Title ──────────────────────────────────────────────────────────────
cells.append(markdown_cell(
    "# EAEDS Voice Pipeline — Colab Notebook\n"
    "**Emotion-Aware Emergency Dispatch System**  \n"
    "Run each cell **top-to-bottom**. "
    "The last cell starts the API server and prints your public ngrok URL."
))

# ── Cell 1: Installs ──────────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 1: INSTALL DEPENDENCIES\n",
    "# ================================================\n",
    '!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"\n',
    '!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes\n',
    "!pip install -q fastapi uvicorn pyngrok nest-asyncio sentence-transformers\n",
    "!pip install -q faster-whisper opensmile soundfile scikit-learn\n",
]))

# ── Cell 2: Imports ───────────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 2: IMPORTS\n",
    "# ================================================\n",
    "import os, io, re, json, torch, base64, tempfile\n",
    "import numpy as np\n",
    "import soundfile as sf\n",
    "from datetime import datetime\n",
    "from typing import List, Optional, Dict\n",
    "from unsloth import FastLanguageModel\n",
    "from transformers import TextIteratorStreamer\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from faster_whisper import WhisperModel\n",
    "import opensmile\n",
    "from threading import Thread\n",
    "import asyncio\n",
    "from fastapi import FastAPI, UploadFile, File, Form\n",
    "from fastapi.responses import JSONResponse, StreamingResponse\n",
    "from pydantic import BaseModel\n",
    "from pyngrok import ngrok\n",
    "import uvicorn\n",
    "import nest_asyncio\n",
    "import logging, warnings\n",
    'warnings.filterwarnings("ignore", category=FutureWarning)\n',
    'warnings.filterwarnings("ignore", category=UserWarning)\n',
    'logging.getLogger("transformers").setLevel(logging.ERROR)\n',
    'logging.getLogger("unsloth").setLevel(logging.ERROR)\n',
    'print("Imports OK")\n',
]))

# ── Cell 3: Config ────────────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 3: CONFIG  ← Update NGROK_AUTH_TOKEN if expired\n",
    "# ================================================\n",
    'MODEL_ID            = "unsloth/llama-3-8b-Instruct-bnb-4bit"\n',
    'EMBED_MODEL_ID      = "all-MiniLM-L6-v2"\n',
    'WHISPER_MODEL_SIZE  = "small"  # tiny / base / small / medium\n',
    'NGROK_AUTH_TOKEN    = "379pHHHLQtvbt7YGRViXrOqhk0u_5AkwqBt88Pn5R64gQ6AoN"\n',
    "MAX_SEQ_LENGTH      = 2048\n",
    "dtype               = None\n",
    "load_in_4bit        = True\n",
    "\n",
    "active_calls: Dict[str, List[str]] = {}\n",
    'EMOTION_LABELS = ["Calm", "Nervous", "Panicked", "Angry", "Distressed"]\n',
    'print("Config OK")\n',
]))

# ── Cell 4: Load Models ───────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 4: LOAD ALL MODELS  (takes 5-10 min first time)\n",
    "# ================================================\n",
    "print('Loading Embeddings...')\n",
    "embed_model = SentenceTransformer(EMBED_MODEL_ID)\n",
    "print('Embeddings loaded!')\n",
    "\n",
    "print('Loading Llama-3 (this takes a few minutes)...')\n",
    "model, tokenizer = FastLanguageModel.from_pretrained(\n",
    "    model_name=MODEL_ID,\n",
    "    max_seq_length=MAX_SEQ_LENGTH,\n",
    "    dtype=dtype,\n",
    "    load_in_4bit=load_in_4bit,\n",
    ")\n",
    "FastLanguageModel.for_inference(model)\n",
    "print('Llama-3 loaded!')\n",
    "\n",
    "print('Loading Faster-Whisper...')\n",
    "whisper_model = WhisperModel(WHISPER_MODEL_SIZE, device='cuda', compute_type='float16')\n",
    "print('Faster-Whisper loaded!')\n",
    "\n",
    "print('Loading OpenSMILE...')\n",
    "smile = opensmile.Smile(\n",
    "    feature_set=opensmile.FeatureSet.eGeMAPSv02,\n",
    "    feature_level=opensmile.FeatureLevel.Functionals,\n",
    ")\n",
    "print('OpenSMILE loaded!')\n",
    "print('\\nALL MODELS LOADED SUCCESSFULLY!')\n",
]))

# ── Cell 5: RAG Knowledge Base ────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 5: NUMPY VECTOR STORE (RAG)\n",
    "# ================================================\n",
    "knowledge_chunks = []\n",
    "knowledge_embeddings = None\n",
    "\n",
    "def build_knowledge_base(text_data):\n",
    "    global knowledge_chunks, knowledge_embeddings\n",
    '    raw_chunks = [line.strip() for line in text_data.split("\\n") if len(line) > 20]\n',
    "    if not raw_chunks:\n",
    "        return\n",
    "    print(f'Embedding {len(raw_chunks)} chunks...')\n",
    "    embeddings = embed_model.encode(raw_chunks, convert_to_numpy=True)\n",
    "    knowledge_chunks = raw_chunks\n",
    "    knowledge_embeddings = embeddings\n",
    "    print(f'Learned {len(knowledge_chunks)} facts!')\n",
    "\n",
    "def retrieve_context(query, k=3):\n",
    "    if knowledge_embeddings is None or len(knowledge_chunks) == 0:\n",
    "        return []\n",
    "    query_vec = embed_model.encode([query], convert_to_numpy=True)\n",
    "    scores = np.dot(knowledge_embeddings, query_vec.T).flatten()\n",
    "    top_k_indices = np.argsort(scores)[-k:][::-1]\n",
    "    return [knowledge_chunks[idx] for idx in top_k_indices]\n",
    "\n",
    "# Knowledge base starts empty. Upload documents via the UI.\n",
]))

# ── Cell 6: Helper Functions ──────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 6: HELPER FUNCTIONS (STT, Emotion, Threat)\n",
    "# ================================================\n",
    "\n",
    "def transcribe_audio(audio_path: str) -> str:\n",
    '    """Run Faster-Whisper on an audio file and return the transcript."""\n',
    "    segments, info = whisper_model.transcribe(\n",
    "        audio_path,\n",
    "        beam_size=1,\n",
    '        language="en",\n',
    "        vad_filter=True,\n",
    "        vad_parameters=dict(min_silence_duration_ms=500),\n",
    '        initial_prompt="Emergency 911 call. Fire, police, medical. Address, emergency situation."\n',
    "    )\n",
    '    transcript = " ".join([seg.text.strip() for seg in segments])\n',
    "    h_patterns = [\n",
    '        r"^thank you", r"^thanks for watching", r"^bye$", r"^you$",\n',
    '        r"^subtitles by", r"^please subscribe", r"^skii-", r"^\\.$"\n',
    "    ]\n",
    "    for pattern in h_patterns:\n",
    "        if re.search(pattern, transcript.strip().lower()):\n",
    "            print(f\"  Whisper hallucination detected ('{transcript}') - skipping.\")\n",
    '            return ""\n',
    "    print(f'  STT Transcript: {transcript}')\n",
    "    return transcript\n",
    "\n",
    "\n",
    "def extract_emotion_from_audio(audio_path: str) -> str:\n",
    '    """Run OpenSMILE on audio and classify emotion from acoustic features."""\n',
    "    try:\n",
    "        signal, sr = sf.read(audio_path)\n",
    "        if signal.dtype != np.float32:\n",
    "            signal = signal.astype(np.float32)\n",
    "        features = smile.process_signal(signal, sr)\n",
    '        f0_mean  = features["F0semitoneFrom27.5Hz_sma3nz_amean"].values[0]\n',
    '        f0_std   = features["F0semitoneFrom27.5Hz_sma3nz_stddevNorm"].values[0]\n',
    '        loudness = features["loudness_sma3_amean"].values[0]\n',
    '        jitter   = features["jitterLocal_sma3nz_amean"].values[0]\n',
    '        shimmer  = features["shimmerLocaldB_sma3nz_amean"].values[0]\n',
    '        hnr      = features["HNRdBACF_sma3nz_amean"].values[0]\n',
    "        if f0_mean > 30 and loudness > 0.5 and jitter > 0.02:\n",
    '            emotion = "Panicked"\n',
    "        elif f0_mean > 25 and f0_std > 0.3 and loudness > 0.3:\n",
    '            emotion = "Angry"\n',
    "        elif jitter > 0.015 or shimmer > 3.0:\n",
    '            emotion = "Nervous"\n',
    "        elif f0_std > 0.2 and loudness < 0.2:\n",
    '            emotion = "Distressed"\n',
    "        else:\n",
    '            emotion = "Calm"\n',
    "        print(f'  Emotion: {emotion} | F0={f0_mean:.1f}, Loud={loudness:.2f}, Jitter={jitter:.4f}')\n",
    "        return emotion\n",
    "    except Exception as e:\n",
    "        print(f'  Emotion Error: {e}')\n",
    '        return "Neutral"\n',
    "\n",
    "\n",
    "def classify_threat(text: str, emotion: str) -> dict:\n",
    '    """Keyword + emotion heuristic threat classifier."""\n',
    "    text_lower = text.strip().lower()\n",
    '    if len(text_lower) < 3 or text_lower in ["", "um", "uh", "hmm"]:\n',
    '        return {"is_threat": False, "classification": "silence", "confidence": 0.95}\n',
    '    prank_keywords = ["yo what\'s up", "lol", "haha", "just kidding", "prank", "testing"]\n',
    "    if any(kw in text_lower for kw in prank_keywords):\n",
    '        return {"is_threat": False, "classification": "prank", "confidence": 0.85}\n',
    '    emergency_keywords = [\n',
    '        "help", "fire", "gun", "shoot", "stab", "blood", "dying",\n',
    '        "cant breathe", "can\'t breathe", "heart attack", "overdose",\n',
    '        "break in", "breaking in", "robbery", "assault", "crash",\n',
    '        "accident", "unconscious", "not breathing", "choking",\n',
    '        "someone in my house", "intruder", "hurry", "please help"\n',
    "    ]\n",
    "    has_emergency = any(kw in text_lower for kw in emergency_keywords)\n",
    '    high_emotion = emotion in ["Panicked", "Angry", "Distressed"]\n',
    "    if has_emergency:\n",
    '        return {"is_threat": True, "classification": "emergency", "confidence": 0.95}\n',
    "    elif high_emotion and len(text_lower) > 10:\n",
    '        return {"is_threat": True, "classification": "potential_emergency", "confidence": 0.75}\n',
    "    else:\n",
    '        return {"is_threat": True, "classification": "general_call", "confidence": 0.60}\n',
    "\n",
    'print("Helper functions defined OK")\n',
]))

# ── Cell 7: LLM Response Functions ───────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 7: LLM RESPONSE FUNCTIONS\n",
    "# ================================================\n",
    "\n",
    "def _build_system_prompt(city, state, emotion, context_text, streaming=False):\n",
    "    word_limit = 'under 12 words' if streaming else 'under 15 words'\n",
    "    history_section = f'### RETRIEVED HISTORY\\n{context_text}\\n' if context_text.strip() else ''\n",
    "    return f\"\"\"### ROLE\n",
    "You are a 911 Dispatcher for {city}, {state}. The caller sounds {emotion}.\n",
    "CRITICAL: Be extremely concise. {word_limit}. Short, punchy sentences. No filler.\n",
    "\n",
    "{history_section}\n",
    "\n",
    "### CRITICAL OUTPUT FORMAT\n",
    "When you identify a location:  <ACTION>UPDATE_MAP: [Full Address]</ACTION>\n",
    "When you dispatch services:    <ACTION>DISPATCH: [Service1, Service2]</ACTION>\n",
    "When call is ending:           <ACTION>END_CALL</ACTION>\n",
    "\n",
    "### RULES\n",
    "- STOP after your response. Do NOT continue as the caller.\n",
    "- Use TAGS the MOMENT you have the info. Do not delay.\n",
    "- Fire=Fire, Injuries=EMS, Crime=Police.\"\"\"\n",
    "\n",
    "\n",
    "def _parse_tags(raw_text):\n",
    "    import re\n",
    "    location_extracted = ''\n",
    "    dispatched_services = []\n",
    "    map_match = re.search(r'<\\s*ACTION\\s*>\\s*UPDATE_MAP:\\s*(.*?)(?:<\\s*/\\s*ACTION\\s*>|$)', raw_text, re.IGNORECASE | re.DOTALL)\n",
    "    if not map_match:\n",
    "        map_match = re.search(r'UPDATE_MAP:\\s*(.+?)(?:\\.|$)', raw_text, re.IGNORECASE)\n",
    "    if map_match:\n",
    "        location_extracted = map_match.group(1).strip().rstrip('.')\n",
    "    dispatch_match = re.search(r'<\\s*ACTION\\s*>\\s*DISPATCH:\\s*(.*?)(?:<\\s*/\\s*ACTION\\s*>|$)', raw_text, re.IGNORECASE | re.DOTALL)\n",
    "    if not dispatch_match:\n",
    "        dispatch_match = re.search(r'DISPATCH:\\s*(.+?)(?:\\.|$)', raw_text, re.IGNORECASE)\n",
    "    if dispatch_match:\n",
    "        dispatched_services = [s.strip() for s in dispatch_match.group(1).strip().rstrip('.').split(',')]\n",
    "    clean = re.sub(r'<\\s*ACTION\\s*>.*?(?:<\\s*/\\s*ACTION\\s*>|$)', '', raw_text, flags=re.IGNORECASE | re.DOTALL).strip()\n",
    "    clean = re.sub(r'UPDATE_MAP:\\s*[^\\.\\n]+\\.?', '', clean, flags=re.IGNORECASE).strip()\n",
    "    clean = re.sub(r'DISPATCH:\\s*[^\\.\\n]+\\.?', '', clean, flags=re.IGNORECASE).strip()\n",
    "    clean = re.sub(r'END_CALL\\b', '', clean, flags=re.IGNORECASE).strip()\n",
    "    clean = re.sub(r'\\s{2,}', ' ', clean).strip()\n",
    "    end_call = bool(re.search(r'(?:<\\s*ACTION\\s*>\\s*)?END_CALL\\s*(?:<\\s*/\\s*ACTION\\s*>|$)', raw_text, re.IGNORECASE))\n",
    "    return clean, location_extracted, dispatched_services, end_call\n",
    "\n",
    "\n",
    "def generate_llm_response(text, emotion, phone, city, state):\n",
    "    global active_calls\n",
    "    if phone not in active_calls:\n",
    "        active_calls[phone] = []\n",
    "    context_list = retrieve_context(text)\n",
    "    context_text = '\\n'.join([f'- {c}' for c in context_list])\n",
    "    system_prompt = _build_system_prompt(city, state, emotion, context_text)\n",
    "    history_str = ''.join(active_calls[phone][-6:])\n",
    "    current_turn = f'<|start_header_id|>user<|end_header_id|>\\n\\nCaller: {text}<|eot_id|><|start_header_id|>assistant<|end_header_id|>'\n",
    "    prompt = f'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\\n\\n{system_prompt}<|eot_id|>{history_str}{current_turn}'\n",
    "    inputs = tokenizer([prompt], return_tensors='pt').to('cuda')\n",
    "    outputs = model.generate(**inputs, max_new_tokens=128, use_cache=True,\n",
    "                             repetition_penalty=1.2, temperature=0.7, do_sample=True,\n",
    "                             pad_token_id=tokenizer.eos_token_id)\n",
    "    generated = tokenizer.batch_decode(outputs[:, inputs.input_ids.shape[1]:], skip_special_tokens=True)[0]\n",
    "    raw = generated.split('Caller:')[0].split('Dispatcher:')[0].strip()\n",
    "    clean, loc, dispatch, end_call = _parse_tags(raw)\n",
    "    full_turn = f'<|start_header_id|>user<|end_header_id|>\\n\\nCaller: {text}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\\n\\n{clean}<|eot_id|>'\n",
    "    active_calls[phone].append(full_turn)\n",
    "    return {'response': clean, 'context_used': context_list, 'location_extracted': loc,\n",
    "            'dispatched_services': dispatch, 'end_call': end_call}\n",
    "\n",
    "\n",
    "async def generate_llm_stream(text, emotion, phone, city, state):\n",
    "    global active_calls\n",
    "    if phone not in active_calls:\n",
    "        active_calls[phone] = []\n",
    "    context_list = retrieve_context(text)\n",
    "    context_text = '\\n'.join([f'- {c}' for c in context_list])\n",
    "    system_prompt = _build_system_prompt(city, state, emotion, context_text, streaming=True)\n",
    "    history_str = ''.join(active_calls[phone][-6:])\n",
    "    current_turn = f'<|start_header_id|>user<|end_header_id|>\\n\\nCaller: {text}<|eot_id|><|start_header_id|>assistant<|end_header_id|>'\n",
    "    prompt = f'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\\n\\n{system_prompt}<|eot_id|>{history_str}{current_turn}'\n",
    "    inputs = tokenizer([prompt], return_tensors='pt').to('cuda')\n",
    "    streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)\n",
    "    gen_kwargs = dict(**inputs, streamer=streamer, max_new_tokens=128, use_cache=True,\n",
    "                      repetition_penalty=1.2, temperature=0.7, do_sample=True,\n",
    "                      pad_token_id=tokenizer.eos_token_id)\n",
    "    Thread(target=model.generate, kwargs=gen_kwargs).start()\n",
    "    full_text = ''\n",
    "    buf = ''\n",
    "    yielded = set()\n",
    "    punctuations = ['. ', '! ', '? ', '.\\n', '!\\n', '?\\n']\n",
    "    for chunk in streamer:\n",
    "        full_text += chunk\n",
    "        buf += chunk\n",
    "        for p in punctuations:\n",
    "            if p in buf:\n",
    "                parts = buf.split(p, 1)\n",
    "                sentence = parts[0] + p.strip()\n",
    "                buf = parts[1] if len(parts) > 1 else ''\n",
    "                clean_s = re.sub(r'<\\s*ACTION\\s*>.*?(?:<\\s*/\\s*ACTION\\s*>|$)', '', sentence, flags=re.IGNORECASE | re.DOTALL).strip()\n",
    "                if (clean_s and 'Dispatcher:' not in clean_s and 'Caller:' not in clean_s\n",
    "                        and not any(k in clean_s.upper() for k in ['DISPATCH:', 'UPDATE_MAP:', 'END_CALL'])\n",
    "                        and len(re.sub(r'[^\\w\\s]', '', clean_s).strip()) > 0\n",
    "                        and clean_s.lower() not in yielded):\n",
    "                    yielded.add(clean_s.lower())\n",
    "                    yield json.dumps({'event': 'sentence', 'text': clean_s}) + '\\n'\n",
    "        await asyncio.sleep(0.01)\n",
    "    if buf.strip():\n",
    "        clean_s = re.sub(r'<\\s*ACTION\\s*>.*?(?:<\\s*/\\s*ACTION\\s*>|$)', '', buf, flags=re.IGNORECASE | re.DOTALL).strip()\n",
    "        if (clean_s and 'Dispatcher:' not in clean_s and 'Caller:' not in clean_s\n",
    "                and not any(k in clean_s.upper() for k in ['DISPATCH:', 'UPDATE_MAP:', 'END_CALL'])\n",
    "                and len(re.sub(r'[^\\w\\s]', '', clean_s).strip()) > 0\n",
    "                and clean_s.lower() not in yielded):\n",
    "            yield json.dumps({'event': 'sentence', 'text': clean_s}) + '\\n'\n",
    "    full_text = full_text.split('Caller:')[0].split('Dispatcher:')[0].strip()\n",
    "    clean, loc, dispatch, end_call = _parse_tags(full_text)\n",
    "    full_turn = f'<|start_header_id|>user<|end_header_id|>\\n\\nCaller: {text}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\\n\\n{clean}<|eot_id|>'\n",
    "    active_calls[phone].append(full_turn)\n",
    "    yield json.dumps({'event': 'final_meta', 'response': clean, 'context_used': context_list,\n",
    "                      'location_extracted': loc, 'dispatched_services': dispatch, 'end_call': end_call}) + '\\n'\n",
    "\n",
    'print("LLM functions defined OK")\n',
]))

# ── Cell 8: FastAPI App ───────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 8: FASTAPI APP ENDPOINTS\n",
    "# ================================================\n",
    "app = FastAPI(title='EAEDS Voice Pipeline')\n",
    "\n",
    "class ChatRequest(BaseModel):\n",
    "    phone_number: str\n",
    "    message: str\n",
    "    city: str = 'Unknown City'\n",
    "    state: str = 'Unknown State'\n",
    "    emotion: str = 'Neutral'\n",
    "    reset: bool = False\n",
    "\n",
    "@app.post('/upload_knowledge')\n",
    "async def upload_file(file: UploadFile = File(...)):\n",
    "    content = await file.read()\n",
    "    text = content.decode('utf-8')\n",
    "    build_knowledge_base(text)\n",
    "    return {'status': 'success', 'message': f'Learned {len(knowledge_chunks)} documents.'}\n",
    "\n",
    "@app.post('/chat')\n",
    "async def generate_response(req: ChatRequest):\n",
    "    global active_calls\n",
    "    if req.reset or req.phone_number not in active_calls:\n",
    "        active_calls[req.phone_number] = []\n",
    "    result = generate_llm_response(text=req.message, emotion=req.emotion,\n",
    "                                   phone=req.phone_number, city=req.city, state=req.state)\n",
    "    return {'response': result['response'], 'context_used': result['context_used'],\n",
    "            'call_id': req.phone_number, 'location_extracted': result['location_extracted'],\n",
    "            'dispatched_services': result['dispatched_services'], 'end_call': result['end_call'],\n",
    "            'title': '', 'live_summary': '', 'final_summary': ''}\n",
    "\n",
    "@app.post('/stream-voice')\n",
    "async def stream_voice(audio: UploadFile = File(...), phone_number: str = Form(...),\n",
    "                        city: str = Form('Unknown City'), state: str = Form('Unknown State'),\n",
    "                        reset: str = Form('false')):\n",
    "    start_time = datetime.now()\n",
    "    if reset.lower() == 'true' and phone_number in active_calls:\n",
    "        active_calls[phone_number] = []\n",
    "    audio_bytes = await audio.read()\n",
    "    with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:\n",
    "        tmp.write(audio_bytes)\n",
    "        tmp_path = tmp.name\n",
    "    transcript_task = asyncio.to_thread(transcribe_audio, tmp_path)\n",
    "    emotion_task    = asyncio.to_thread(extract_emotion_from_audio, tmp_path)\n",
    "    transcript, emotion = await asyncio.gather(transcript_task, emotion_task)\n",
    "    hallucinations = ['thank you.', 'thank you', 'thanks for watching.', 'bye.', 'bye']\n",
    "    if transcript and transcript.strip().lower() in hallucinations:\n",
    "        transcript = ''\n",
    "    if not transcript or len(transcript.strip()) < 2:\n",
    "        os.unlink(tmp_path)\n",
    "        async def _empty():\n",
    "            yield json.dumps({'event': 'final_meta', 'response': '', 'context_used': [],\n",
    "                              'location_extracted': '', 'dispatched_services': [],\n",
    "                              'end_call': False, 'transcript': ''}) + '\\n'\n",
    "        return StreamingResponse(_empty(), media_type='text/event-stream')\n",
    "    os.unlink(tmp_path)\n",
    "    threat_result = classify_threat(transcript, emotion)\n",
    "    async def _pipeline():\n",
    "        yield json.dumps({'event': 'start_turn', 'transcript': transcript,\n",
    "                          'emotion': emotion, 'threat': threat_result}) + '\\n'\n",
    "        if threat_result['is_threat']:\n",
    "            async for chunk in generate_llm_stream(transcript, emotion, phone_number, city, state):\n",
    "                yield chunk\n",
    "        else:\n",
    "            fake_res = 'This line is for emergencies only. If you have a real emergency, please describe it.'\n",
    "            yield json.dumps({'event': 'sentence', 'text': fake_res}) + '\\n'\n",
    "            yield json.dumps({'event': 'final_meta', 'response': fake_res, 'context_used': [],\n",
    "                              'location_extracted': '', 'dispatched_services': [], 'end_call': False}) + '\\n'\n",
    "    return StreamingResponse(_pipeline(), media_type='text/event-stream')\n",
    "\n",
    "@app.get('/health')\n",
    "async def health():\n",
    "    return {'status': 'ok', 'models': {'llm': 'llama-3-8b-4bit',\n",
    "            'stt': f'faster-whisper-{WHISPER_MODEL_SIZE}',\n",
    "            'emotion': 'opensmile-eGeMAPSv02', 'rag': EMBED_MODEL_ID}}\n",
    "\n",
    "print('FastAPI app defined OK')\n",
]))

# ── Cell 9: Run Server ────────────────────────────────────────────────────────
cells.append(code_cell([
    "# ================================================\n",
    "#  CELL 9: START SERVER  (run this LAST)\n",
    "# ================================================\n",
    "ngrok.set_auth_token(NGROK_AUTH_TOKEN)\n",
    "public_url = ngrok.connect(8000).public_url\n",
    "print(f'\\n API IS LIVE AT: {public_url}')\n",
    "print(f'   POST {public_url}/chat           (text endpoint)')\n",
    "print(f'   POST {public_url}/stream-voice   (audio pipeline)')\n",
    "print(f'   GET  {public_url}/health         (status check)')\n",
    "print()\n",
    "print('COPY the URL above and paste it into server/main.py as COLAB_API_URL')\n",
    "nest_asyncio.apply()\n",
    "config = uvicorn.Config(app, port=8000, host='0.0.0.0')\n",
    "server = uvicorn.Server(config)\n",
    "await server.serve()\n",
]))

# ── Write notebook ─────────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        },
        "accelerator": "GPU",
        "colab": {
            "name": "EAEDS_Voice_Pipeline.ipynb",
            "provenance": [],
            "gpuType": "T4"
        }
    },
    "cells": cells
}

output_path = "colab_rag_api.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"\nSuccessfully created: {output_path}")
print(f"Cell count: {len(cells)}")
print("Upload this .ipynb file to Google Colab!")
